[secrets]
[[rules]]
description = "Custom API Key Rule"
regex = '''(sk_test_[a-zA-Z0-9]{10})'''
tags = ["api-key"]

[[rules]]
description = "Custom Password Rule"
regex = '''(supersecretpassword[0-9]+)'''
tags = ["password"]