title = "Custom Gitleaks Config"

[secrets]

[[rules]]
id = "api-key-rule"
description = "Custom API Key Rule"
regex = '''(sk_test_[a-zA-Z0-9]{10})'''
tags = ["api-key"]

[[rules]]
id = "password-rule"
description = "Custom Password Rule"
regex = '''(supersecretpassword[0-9]+)'''
tags = ["password"]

[allowlist]
description = "Ignore downloaded tools and vendor binaries"
paths = [
  '''Day-1/tools/.*'''
]
